using System;
using System.Text;
using core;

namespace impl
{
    /// <summary>
    /// Generates protobuf schemas for the engine C++ backend. Data remains in
    /// protobuf-net generated .dat files and is never embedded in C++.
    /// </summary>
    public sealed class CppGenCode
    {
        private const string PackageName = "recoil.live.config.proto";

        public string Generate(DefMetaData meta)
        {
            ValidateIdentifier(meta.ClassName, "table");
            ValidateIdentifier(meta.MgrClassName, "manager");

            var output = new StringBuilder();
            output.AppendLine("// Generated by config_excel. Do not edit manually.");
            output.AppendLine("syntax = \"proto3\";");
            output.AppendLine();
            output.AppendLine("package " + PackageName + ";");
            output.AppendLine("option optimize_for = LITE_RUNTIME;");
            if (UsesDateTime(meta))
                output.AppendLine("import \"protobuf-net/bcl.proto\";");
            output.AppendLine();

            AppendMessage(output, meta);
            AppendManager(output, meta);
            return output.ToString();
        }

        private static void AppendMessage(StringBuilder output, DefMetaData meta)
        {
            output.AppendLine("message " + meta.ClassName + " {");
            for (var index = 0; index < meta.Fileds.Count; ++index)
            {
                var field = meta.Fileds[index];
                ValidateIdentifier(field.Name, "field");
                output.AppendLine("\t" + GetProtoFieldType(field) + " " + field.Name + " = " + (index + 1) + ";");
            }
            output.AppendLine("}");
            output.AppendLine();
        }

        private static void AppendManager(StringBuilder output, DefMetaData meta)
        {
            output.AppendLine("message " + meta.MgrClassName + " {");
            output.AppendLine("\tmap<" + GetProtoType(meta.Key.Type.Type) + ", " + meta.ClassName + "> entries = 1;");
            output.AppendLine("}");
        }

        private static string GetProtoFieldType(FiledMetaData field)
        {
            if (field.TypeEnum == EFiledType.Array)
                throw new NotSupportedException("C++ protobuf backend does not support array field: " + field.Name);
            if (field.TypeEnum == EFiledType.CustomType)
                throw new NotSupportedException("C++ protobuf backend does not support custom field: " + field.Name);

            if (field.TypeEnum == EFiledType.Dictionary)
            {
                var arguments = field.Type.Type.GetGenericArguments();
                if (arguments.Length != 2)
                    throw new NotSupportedException("C++ protobuf backend only supports two-parameter dictionaries: " + field.Name);
                return "map<" + GetProtoType(arguments[0]) + ", " + GetProtoType(arguments[1]) + ">";
            }

            return GetProtoType(field.Type.Type);
        }

        private static string GetProtoType(Type type)
        {
            if (type == typeof(string)) return "string";
            if (type == typeof(bool)) return "bool";
            if (type == typeof(double)) return "double";
            if (type == typeof(float)) return "float";
            if (type == typeof(int) || type == typeof(short)) return "int32";
            if (type == typeof(long)) return "int64";
            if (type == typeof(byte)) return "uint32";
            if (type == typeof(DateTime)) return "bcl.DateTime";
            throw new NotSupportedException("C++ protobuf backend does not support field type: " + type.FullName);
        }

        private static bool UsesDateTime(DefMetaData meta)
        {
            foreach (var field in meta.Fileds)
            {
                if (field.Type.Type == typeof(DateTime))
                    return true;
                if (field.TypeEnum == EFiledType.Dictionary)
                {
                    var arguments = field.Type.Type.GetGenericArguments();
                    if (arguments.Length == 2 && (arguments[0] == typeof(DateTime) || arguments[1] == typeof(DateTime)))
                        return true;
                }
            }
            return false;
        }

        private static void ValidateIdentifier(string value, string kind)
        {
            if (string.IsNullOrEmpty(value) || !(char.IsLetter(value[0]) || value[0] == '_'))
                throw new NotSupportedException("C++ protobuf backend requires a valid " + kind + " identifier: " + value);

            for (var index = 1; index < value.Length; ++index)
            {
                if (!(char.IsLetterOrDigit(value[index]) || value[index] == '_'))
                    throw new NotSupportedException("C++ protobuf backend requires a valid " + kind + " identifier: " + value);
            }
        }
    }
}
